development:
  adapter: postgresql
  database: trainees_exam_dev
  pool: 5
  timeout: 5000
  username: dev
  password: dev

test:
  adapter: postgresql
  database: trainees_exam_test
  pool: 5
  timeout: 5000
  username: dev
  password: dev

production:
  adapter: postgresql
  database: trainees_exam_production
  pool: 5
  timeout: 5000
  username: dev
  password: dev
